import { useState, ReactNode } from 'react';

import Head from 'next/head';
import { useRouter } from 'next/router';

import Navbar from './Navbar';
import Sidebar from './Sidebar';
import useMediaQuery from '../../hooks/useMediaQuery';

type LayoutProps = {
  children: ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const router = useRouter();
  const isSmallScreen = useMediaQuery('(max-width: 1024px)');
  const [isOpen, setIsOpen] = useState<boolean>(() => false);

  const pageTitle = router.pathname === '/products' ? 'Products' : 'Carts';

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by home" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar pageTitle={pageTitle} />
      <Sidebar
        isOpen={isOpen}
        setIsOpen={setIsOpen}
        isSmallScreen={isSmallScreen}
      />
      <main
        className={`bg-gray-200/80 relative w-full min-h-screen pt-24 pb-12 pr-5 ${
          isSmallScreen ? 'px-5' : isOpen ? 'pl-80' : 'pl-28'
        }`}
      >
        {children}
      </main>
    </>
  );
};

export default Layout;
